dyrane is awesome

diff --git a/0x0C-web_server/1-install_nginx_web_server b/0x0C-web_server/1-install_nginx_web_server
--- a/0x0C-web_server/1-install_nginx_web_server
+++ b/0x0C-web_server/1-install_nginx_web_server
@@ -30,12 +30,38 @@
 apt-get -y update
 apt-get -y install nginx
 
-# Allow incoming HTTP traffic in the Uncomplicated Firewall (UFW)
-ufw allow 'Nginx HTTP'
-
 # Create an HTML file with "Hello World!" content
 # in the default Nginx web directory
 echo 'Hello World!' > /var/www/html/index.html
 
-# Start the Nginx service
-service nginx start
+# Ensure Nginx is listening on port 80
+if ! grep -q "listen 80;" /etc/nginx/sites-available/default; then
+    sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
+fi
+
+# Restart Nginx to apply the changes
+service nginx restart
+
+# Check Nginx Configuration
+nginx_test_output=$(nginx -t 2>&1)
+
+# Verify if Nginx configuration test is successful
+if [[ $nginx_test_output == *"test is successful"* ]]; then
+    echo "Nginx configuration test: PASSED"
+    # Re-run checks
+    ./1-install_nginx_web_server > /dev/null 2>&1
+
+    # Verify the response
+    curl_output=$(curl -s localhost)
+
+    if [[ "$curl_output" == "Hello World!" ]]; then
+        echo "Nginx serves 'Hello World!': PASSED"
+        exit 0
+    else
+        echo "Nginx serves 'Hello World!': FAILED"
+        exit 1
+    fi
+else
+    echo "Nginx configuration test: FAILED"
+    exit 1
+fi
