dyrane is awesome

diff --git a/0x0C-web_server/1-install_nginx_web_server b/0x0C-web_server/1-install_nginx_web_server
--- a/0x0C-web_server/1-install_nginx_web_server
+++ b/0x0C-web_server/1-install_nginx_web_server
@@ -41,16 +41,16 @@ echo 'Hello World!' > /var/www/html/index.html
 service nginx start
 
 # Verify Nginx installation by querying the root / (local and remote)
-#local_response=$(curl -s http://localhost)
-#remote_response=$(curl -s http://$(hostname -I | awk '{print $1}'))
-#
-#if [[ "$local_response" == *"Hello World!"* &&
-#      "$remote_response" == *"Hello World!"* ]]; then
-#    echo "Nginx installation successful."
-#else
-#    echo "Nginx installation failed or does not serve 'Hello World!'"
-#    exit 1
-#fi
-#
+local_response=$(curl -s http://localhost)
+remote_response=$(curl -s http://$(hostname -I | awk '{print $1}'))
+
+if [[ "$local_response" == *"Hello World!"* &&
+      "$remote_response" == *"Hello World!"* ]]; then
+    echo "Nginx installation successful."
+else
+    echo "Nginx installation failed or does not serve 'Hello World!'"
+    exit 1
+fi
+
 # Exit with success
-#exit 0
+exit 0
